# Generated by Django 5.2.3 on 2025-06-15 14:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter a Language (Doesn't have to be a language we have yet!)",
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="genre",
            name="genre_name_case_insensitive_unique",
        ),
        migrations.RemoveField(
            model_name="book",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="book",
            name="summary",
        ),
        migrations.AddConstraint(
            model_name="genre",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="language_name_case_insensitive_unique",
                violation_error_message="Languge already exists (case insensitive match)",
            ),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="genre_name_case_insensitive_unique",
                violation_error_message="Genre already exists (case insensitive match)",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="language",
            field=models.ManyToManyField(
                help_text="Select a language(s) for this book", to="catalog.language"
            ),
        ),
    ]
