# Generated by Django 5.2.3 on 2025-06-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
                max_length=13,
                null=True,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="summary",
            field=models.TextField(
                help_text="Enter a brief description of the book",
                max_length=1000,
                null=True,
            ),
        ),
    ]
