# Generated by Django 5.2.3 on 2025-06-15 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_isbn_book_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinstance",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="catalog.language",
            ),
        ),
    ]
