# Generated by Django 5.2.3 on 2025-06-16 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "bio",
                    models.TextField(
                        help_text="Enter a brief personal bio", max_length=5000
                    ),
                ),
                ("email", models.CharField(max_length=50)),
                ("linkedin", models.URLField(max_length=50)),
                ("github", models.URLField(max_length=50)),
                ("cur_job", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("short_desc", models.CharField(max_length=100)),
                ("long_desc", models.CharField(max_length=50)),
                ("start_date", models.DateField(null=True)),
                ("end_date", models.DateField(null=True)),
                (
                    "difficulty",
                    models.CharField(help_text="Difficulty out of 10", max_length=10),
                ),
                ("project_git", models.URLField(max_length=50, null=True)),
                ("live_demo_link", models.URLField(max_length=50, null=True)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("file", models.FileField(upload_to="project_media/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("embed", "Embedded Content (e.g., YouTube/Vimeo)"),
                            ("html_demo", "HTML/JS Interactive Demo"),
                            ("glb_model", "3D GLB Model"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(null=True, to="catalog.skill"),
        ),
        migrations.AddField(
            model_name="project",
            name="tech",
            field=models.ManyToManyField(null=True, to="catalog.technology"),
        ),
    ]
