# Generated by Django 5.2.3 on 2025-06-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skill",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="technology",
            old_name="name",
            new_name="title",
        ),
    ]
