# Generated by Django 5.2.3 on 2025-06-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_name_skill_title_rename_name_technology_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="phone",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(to="catalog.skill"),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech",
            field=models.ManyToManyField(to="catalog.technology"),
        ),
    ]
