# Generated by Django 5.2.3 on 2025-06-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_person_phone_alter_project_skills_alter_project_tech"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="long_desc",
            field=models.TextField(
                help_text="Enter the project description", max_length=5000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="short_desc",
            field=models.TextField(
                help_text="Enter the project description", max_length=100, null=True
            ),
        ),
    ]
