# Generated by Django 5.2.3 on 2025-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_project_long_desc_alter_project_short_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="caption",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
