# Generated by Django 5.2.3 on 2025-06-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_projectimage_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="file",
            field=models.FileField(upload_to=""),
        ),
    ]
