# Generated by Django 5.2.3 on 2025-06-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_projectimage_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectImage",
            new_name="ProjectMedia",
        ),
    ]
