# Generated by Django 5.2.3 on 2025-06-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_projectmedia_long_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmedia",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("embed", "Embedded Content (e.g., YouTube/Vimeo)"),
                    ("html_demo", "Interactive Demo"),
                    ("glb_model", "3D GLB Model"),
                ],
                default="image",
                max_length=20,
            ),
        ),
    ]
