# Generated by Django 5.2.3 on 2025-06-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_projectmedia_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="difficulty",
            field=models.CharField(
                blank=True, help_text="Difficulty out of 10", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="live_demo_link",
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_git",
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(null=True, to="catalog.skill"),
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech",
            field=models.ManyToManyField(null=True, to="catalog.technology"),
        ),
    ]
