# Generated by Django 5.2.3 on 2025-06-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_alter_project_difficulty_alter_project_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmedia",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="long_desc",
            field=models.TextField(
                blank=True,
                help_text="Enter the media description",
                max_length=5000,
                null=True,
            ),
        ),
    ]
